"""
Create a stacked plot of chosen variables against PNBI (neutral beam injeciton power).  
"""
import pandas as pd
from matplotlib import pyplot as plt

df = pd.read_csv('pnbi_averages.csv')  # Dataset generated by main.py
# df = df[df['input']<40]                        # Filter
xdata = df['pnbi']                             # x-data in mega-watts MW  
ydatas = ['modeh','betan','ni0','ti0','taue','tripleprod']          # list of y-variables to include in stacked plot.

# Create stacked plot with shared x-axis ('pnbi')
fig, ax = plt.subplots(len(ydatas), sharex=True)    

# Iterate through chosen y-variables and plot on a separate axis each
for i, var in enumerate(ydatas):
    ydata = df[var]
    yerr = df[f'{var}_std']
    # ax[i].scatter(xdata,ydata,label='Average', s=6, color="red",zorder=5)

    ax[i].errorbar(xdata, y=ydata, yerr=yerr, label='Average', ecolor="black", capsize=2, zorder=1) 
    ax[i].set_ylabel(var)
    
ax[0].set_title('Parameters vs PNBI')
ax[-1].set_xlabel('PNBI (MW)')
plt.legend()
plt.subplots_adjust(hspace=0)
plt.show()


# plt.plot(df['pnbi_input'],df['pnbi']*1e-6)
# plt.xlabel("Input Parameter (MW)")
# plt.ylabel("Measured Parameter (MW)")
# plt.title("Input vs Measured PNBI")
# plt.show()