"""
Create a stacked plot of chosen variables against PNBI (neutral beam injeciton power).  
"""
import pandas as pd
from matplotlib import pyplot as plt

df = pd.read_csv('b0_averages_q.csv')  # Dataset generated by main.py
df = df[df['input']>1]                        # Filter
xdata = df['input']                             # x-data in mega-watts MW  
ydatas = ['modeh','q0','tripleprod']          # list of y-variables to include in stacked plot.

# Create stacked plot with shared x-axis ('pnbi')
fig, ax = plt.subplots(len(ydatas), sharex=True)    

# Iterate through chosen y-variables and plot on a separate axis each
for i, var in enumerate(ydatas):
    ydata = df[var]
    yerr = df[f'{var}_std']
    # ax[i].scatter(xdata,ydata,label='Average', s=6, color="red",zorder=5)

    ax[i].errorbar(xdata, y=ydata, yerr=yerr, label='Average', ecolor="black", capsize=2, zorder=1) 
    ax[i].set_ylabel(var)
    
ax[0].set_title('Parameters vs B0')
ax[-1].set_xlabel('B0 (T)')
plt.legend()
plt.subplots_adjust(hspace=0)
plt.show()